# 项目信息配置
project:
  env: production

# 服务器配置
server:
  port: 9001

# Spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://cdb-39jppy1a.bj.tencentcdb.com:10251/recommendation?characterEncoding=utf8&useSSL=false
    username: linwei
    password: abc88888def
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    ## 默认日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    ##前台数据传输大小
  http:
    multipart:
      max-file-size:1000Mb
      max-request-size:1000Mb
  ##网易系(126/163/yeah)邮箱配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: linwei2917042249@163.com #发送邮件的邮箱地址
    password: abc553197def #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties.mail.smtp.port: 994 #465或者994
    from: linwei2917042249@163.com # 发送邮件的地址，和上面username一致
    #    可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    # redis数据库
    redis :
      host: localhost
      port: 6379
      #      password :
      database : 1
      pool.max-idle : 8
      pool.min-idle : 1
      pool.max-active : 8
      pool.max-wait : -1

# MyBatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml #对应mappers映射xml文件的所在路径
  configuration:
    map-underscore-to-camel-case: true # 使用resultType时自动将下划线转为驼峰命名
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql语句

# 日志配置
logback:
  level: ERROR
  appender: ${project.env}


